### PR TITLE
Add twoFactorCode for two factor authentication

### PR DESCRIPTION
**Pull request by andrewda**

### CODE REVIEW

**Comment by kjsmita6** [comment]
Any way to include getting the code automatically using node-steamcommunity and node-steam-totp? I think that would be more useful since more beginners wouldn't know how to do that, and that's the point of this module.

**Comment by andrewda** [comment]
Sure, I can whip something like that up!

**Comment by andrewda** [comment]
This should work to automatically generate the 2FA code.

**Comment by kjsmita6** [comment]
Will that automatically confirm the trades in the escrow system? Cause that's the whole point of it, most new users won't know how to do that.

**Comment by andrewda** [comment]
Latest commits should do exactly that!

**Comment by kjsmita6** [comment]
Looks good, I'll merge and release on npm on the 9th when it is implemented. Then we'll see if it works. If it doesn't, we'll fix it.

**Comment by andrewda** [comment]
Alright, great!

**Pull request merged**
